import {
  scanConfigControl,
  scanConfigEditor,
  scanConfigField,
  scanConfigModelPicker,
  scanConfigSweep,
  scanConfigSweepValues,
  UI_ELEMENT_ATTRIBUTE,
} from '@locators/scan-config';
import { morphologyLocations, morphologyViewer } from '@locators/viewer';
import { expect, type Locator, type Page } from '@playwright/test';

import type { ScanConfigCase } from './scan-config';
import { ScanConfigUiElement } from './scan-config-ui-elements';

/**
 * Applies a fixture configuration to the scan-configuration editor.
 *
 * The editor chooses each control from the `ui_element` obi-one puts on the
 * field, and records that value on the rendered field. This walker reads it
 * back and dispatches on it, so the two stay in step: a field the application
 * starts rendering differently changes here too, and a `ui_element` this does
 * not handle throws rather than being skipped. Three of the kinds obi-one
 * declares are unhandled in the application dispatcher today, and a silent skip
 * would turn a real gap into a passing test.
 */
export class ScanConfigDriver {
  private readonly editor: ReturnType<typeof scanConfigEditor>;

  constructor(private readonly page: Page) {
    this.editor = scanConfigEditor(page);
  }

  /**
   * Entry names are generated by the editor, not chosen by the fixture, so a
   * reference such as `{ block_dict_name: "distributions", block_name:
   * "exc_delay" }` resolves through what the editor actually created.
   */
  private readonly entryNames = new Map<string, string>();

  async apply(configuration: ScanConfigCase): Promise<void> {
    for (const [rootElement, value] of Object.entries(configuration.config)) {
      // The discriminator is not a field: the schema fixes it.
      if (rootElement === 'type') continue;
      if (!isRecord(value)) throw new Error(`Root element "${rootElement}" must be an object.`);

      // Fields only mount once their root element is open, and the middle
      // column remounts on every change.
      await this.editor.rootElement(rootElement).click();

      if (typeof value.type === 'string') {
        await this.fillBlock(this.editor.block(rootElement), value, rootElement);
        continue;
      }

      await this.fillDictionary(rootElement, value);
    }
  }

  private async fillDictionary(
    rootElement: string,
    entries: Record<string, unknown>
  ): Promise<void> {
    for (const [key, entry] of Object.entries(entries)) {
      if (!isRecord(entry) || typeof entry.type !== 'string') {
        throw new Error(`Entry "${rootElement}.${key}" must carry a "type".`);
      }

      await this.editor.addEntry(rootElement).click();
      await this.editor.variant(entry.type).click();

      const created = await this.selectedEntryName(rootElement);
      this.entryNames.set(`${rootElement}/${key}`, created);

      await this.fillBlock(this.editor.block(rootElement, created), entry, rootElement);
    }
  }

  /** The editor names a new entry itself and selects it; only that one mounts. */
  private async selectedEntryName(rootElement: string): Promise<string> {
    const prefix = `scan-config-block-${rootElement}-`;
    let name = '';

    await expect(async () => {
      const testId = await this.editor.anyBlockOf(rootElement).first().getAttribute('data-testid');
      expect(testId).toContain(prefix);
      name = (testId as string).slice(prefix.length);
      expect(name).not.toBe('');
    }).toPass();

    return name;
  }

  private async fillBlock(
    block: Locator,
    values: Record<string, unknown>,
    rootElement: string
  ): Promise<void> {
    await expect(block).toBeVisible();

    for (const [key, value] of Object.entries(values)) {
      if (key === 'type') continue;

      const field = scanConfigField(block, key);
      if ((await field.count()) === 0) {
        throw new Error(`The editor renders no field "${key}" in block "${rootElement}".`);
      }

      const uiElement = await field.first().getAttribute(UI_ELEMENT_ATTRIBUTE);
      await this.setField(field.first(), uiElement, value, `${rootElement}.${key}`);
    }
  }

  private async setField(
    field: Locator,
    uiElement: string | null,
    value: unknown,
    at: string
  ): Promise<void> {
    switch (uiElement) {
      case ScanConfigUiElement.StringInput:
        await scanConfigControl(field).fill(String(value));
        return;

      case ScanConfigUiElement.BooleanInput: {
        const checkbox = scanConfigControl(field);
        if (value === true) await checkbox.check();
        else await checkbox.uncheck();
        return;
      }

      case ScanConfigUiElement.FloatParameterSweep:
      case ScanConfigUiElement.IntParameterSweep:
      case ScanConfigUiElement.FloatOptional:
        await this.setSweep(field, value, at);
        return;

      case ScanConfigUiElement.StringSelectionEnhanced:
        await this.setPopoverSelection(field, value, at);
        return;

      case ScanConfigUiElement.Reference:
      case ScanConfigUiElement.EntityPropertyDropdown:
        await this.setSelection(field, value, at);
        return;

      case ScanConfigUiElement.ModelSelectorSingle:
        await this.pickModel(field, value, at);
        return;

      case ScanConfigUiElement.MorphologyLocationSelection:
        await this.setMorphologyLocations(value, at);
        return;

      case ScanConfigUiElement.MorphologySectionTypeSelection:
        // The options are labelled by obi-one at run time, so a fixture cannot
        // name them by SWC code. Left unset, the schema default applies.
        throw new Error(
          `${at}: section types are labelled by obi-one at run time, so a fixture cannot set ` +
            'them by SWC code. Leave the field out to keep the schema default.'
        );

      case ScanConfigUiElement.ModelIdentifier:
      case ScanConfigUiElement.ModelIdentifierMultiple:
        // Chosen on the `/new` browse step, which has already run.
        return;

      default:
        throw new Error(
          `${at}: the editor rendered ui_element "${uiElement ?? 'none'}", which this driver ` +
            'does not know how to set. Add a case rather than skipping it.'
        );
    }
  }

  /**
   * A sweep takes one number or a list. Every combination of swept values is one
   * coordinate in the campaign grid, so a list here is what makes a grid.
   */
  private async setSweep(field: Locator, value: unknown, at: string): Promise<void> {
    if (value === null || value === undefined) return;

    if (!Array.isArray(value)) {
      await scanConfigSweepValues(field).first().fill(String(value));
      return;
    }

    if (typeof value[0] !== 'number') {
      throw new Error(`${at}: a sweep takes numbers, got ${JSON.stringify(value[0])}`);
    }

    const sweep = scanConfigSweep(field);
    await sweep.expand.click();
    for (let index = 1; index < value.length; index += 1) {
      await sweep.add.click();
    }

    const inputs = scanConfigSweepValues(field);
    await expect(inputs).toHaveCount(value.length);
    for (const [index, entry] of value.entries()) {
      await inputs.nth(index).fill(String(entry));
    }
  }

  /**
   * Locations on the morphology, which a user picks by clicking neurites in the
   * 3D viewer: the section id is a SONATA index, not something to type, so the
   * fixture declares only how many locations to place and the offset along each.
   *
   * Which pixel of the scene holds a neurite is not knowable in advance, so this
   * works through a spread of points and keeps the ones that land, rather than
   * assuming any single point is over the cell.
   */
  private async setMorphologyLocations(value: unknown, at: string): Promise<void> {
    if (!Array.isArray(value)) {
      throw new Error(`${at}: explicit locations must be a list, one entry per location`);
    }

    const rows = morphologyLocations(this.page);
    await addLocationsFromViewer(this.page, value.length);
    await expect(rows.rows).toHaveCount(value.length);

    for (const [index, entry] of value.entries()) {
      if (!isRecord(entry) || typeof entry.offset !== 'number') {
        throw new Error(`${at}[${index}]: needs an "offset" between 0 and 1`);
      }
      await rows.offset(index).fill(String(entry.offset));
    }
  }

  /**
   * A popover dropdown of its own making: a button that opens a real listbox.
   * The chosen option is addressed by the value it writes, not by its label,
   * which the schema supplies and can be rewritten.
   */
  private async setPopoverSelection(field: Locator, value: unknown, at: string): Promise<void> {
    const option = this.optionValue(value, at);
    if (option === null) return;

    await scanConfigControl(field).click();
    await this.editor.option(option).click();
  }

  /**
   * Picks an entity from the catalogue, which this field opens in a modal
   * rather than a dropdown. The table inside it is the shared entity listing,
   * so the entity is searched for by the name the fixture gives.
   */
  private async pickModel(field: Locator, value: unknown, at: string): Promise<void> {
    if (!isRecord(value) || typeof value.name !== 'string') {
      throw new Error(`${at}: needs a { "name": … } naming the entity to pick`);
    }

    const picker = scanConfigModelPicker(this.page);
    await field.getByTestId('scan-config-select-model').click();

    // The catalogue replaces the editor's middle column rather than opening a
    // dialog, and the editor's own table stays in the document, so everything
    // here is scoped to the picker.
    const catalogue = picker.panel;
    await expect(catalogue).toBeVisible();

    // Searching narrows the catalogue to the one entity, which is what makes
    // ticking it unambiguous below.
    await catalogue.getByTestId('data-grid-search').fill(value.name);
    await expect(
      catalogue.getByRole('row').filter({ hasText: value.name }).first(),
      `No "${value.name}" to pick for ${at}.`
    ).toBeVisible();

    // The grid pins its selection column, so a row's tick is not inside the row
    // holding its name. With one result left there are two ticks on the panel —
    // the header's select-all and the row's — and the row's is the last.
    await catalogue.getByRole('checkbox').last().check();

    await expect(picker.confirm).toBeEnabled();
    await picker.confirm.click();
    await expect(picker.open).toHaveCount(0);
  }

  /** An antd select: a wrapper that opens a list the control owns. */
  private async setSelection(field: Locator, value: unknown, at: string): Promise<void> {
    const option = this.optionValue(value, at);
    if (option === null) return;

    const control = scanConfigControl(field);
    await control.click();

    // Scoped to the list this control owns, which it names through ARIA on its
    // inner input: a dropdown that has just closed is still in the document and
    // still fading out, so a page-wide lookup can land on a stale copy of the
    // same option.
    const listboxId = await control.getByRole('combobox').getAttribute('aria-controls');
    if (!listboxId) throw new Error(`${at}: the dropdown did not open`);

    await this.page
      .locator(`#${listboxId}`)
      .locator('xpath=..')
      .getByTestId(`scan-config-option-${option}`)
      .click();
  }

  /**
   * What the choice writes into the configuration: an enum key, or the name of
   * the block a reference points at. Entry names are generated by the editor,
   * so a fixture's own key is mapped to the entry it created.
   */
  private optionValue(value: unknown, at: string): string | null {
    if (value === null || value === undefined) return null;
    if (typeof value === 'string') return value;

    if (isRecord(value) && typeof value.block_name === 'string') {
      const dictionary = String(value.block_dict_name ?? '');
      const created = this.entryNames.get(`${dictionary}/${value.block_name}`);
      if (!created) {
        throw new Error(
          `${at}: references "${dictionary}.${value.block_name}", which the fixture never adds. ` +
            'A referenced block must appear earlier in the configuration.'
        );
      }
      return created;
    }

    throw new Error(`${at}: cannot select from ${JSON.stringify(value)}`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

/**
 * Clicks the morphology until `count` locations exist.
 *
 * The scene is a rendered neuron, so only some pixels are over a neurite. This
 * sweeps outwards from the middle, keeping every click that adds a row and
 * moving on when one does not.
 */
export async function addLocationsFromViewer(page: Page, count: number): Promise<void> {
  const scene = morphologyViewer(page).scene;
  await expect(scene).toBeVisible();

  const box = await scene.boundingBox();
  if (!box) throw new Error('The 3D viewer has no size, so there is nothing to click.');

  const rows = morphologyLocations(page).rows;
  let placed = await rows.count();

  for (const y of [0.35, 0.45, 0.3, 0.55, 0.25, 0.6, 0.4, 0.65]) {
    for (const x of [0.45, 0.55, 0.4, 0.6, 0.35, 0.65, 0.5, 0.3]) {
      if (placed >= count) return;

      await page.mouse.click(box.x + box.width * x, box.y + box.height * y);

      // A click that misses changes nothing, so this reads the count back rather
      // than assuming the click landed.
      const landed = await expect(async () => {
        expect(await rows.count()).not.toBe(placed);
      })
        .toPass({ timeout: 1_500 })
        .then(() => true)
        .catch(() => false);

      if (landed) placed = await rows.count();
    }
  }

  if (placed < count) {
    throw new Error(
      `Only ${placed} of ${count} locations could be placed: no more of the sampled points ` +
        'landed on a neurite.'
    );
  }
}
